### ISSUE TITLE
option to configure resampling filter for thumbnail generation

### ISSUE THREAD

**Issue by specterpete** [midstar/mediaweb#12]
Thumbnails are currently generated with imaging using the Lanczos resampling filter. This filter is the most resource-consuming, especially on low performance devices like raspberry pi this results in slow thumbnail generation.

I suggest to add a config option to configure the resampling filter (NearestNeighbor, Box, Linear, Hermite, MitchellNetravali, CatmullRom, BSpline, Gaussian, Lanczos, Hann, Hamming, Blackman, Bartlett, Welch, Cosine) so that thumbnail generation can be optimized towards the platform used.

**Comment by midstar** [comment]
Thank you very much for you feedback. I created a new test case, TestGenerateImageThumbnailPerformance, that generates thumbnails with different resampling filters on following branch:

     feature/imaging-resampling-filter

Unfortunately I don't see much performance gain on my ROCK64 SBC nor my Windows PC (see test results below). The quality is quite similar using all the filters except "NearestNeighbor" which has really bad quality. I suggest we simply change the resampling filter from Lanczos to Box since this is the fastest filter with, in my opinion, acceptable quality. 

What do you think about that?

| Filter            | Rock 64     | Windows PC |
|-------------------|-------------|------------|
| Lanczos           | 2998 ms     | 622 ms     |
| CatmullRom        | 2876 ms     | 641 ms     |
| MitchellNetravali | 2884 ms     | 632 ms     | 
| Linear            | 2708 ms     | 555 ms     |
| Box               | 2647 ms     | 532 ms     |
| NearestNeighbor   | 2548 ms     | 520 ms     |

**Comment by specterpete** [comment]
Sounds fine to me. I expected more difference. Thanks for testing it out.

**Comment by specterpete** [comment]
Accidentally closed, sry.

**Comment by specterpete** [comment]
This might also be of interest https://github.com/fawick/speedtest-resize/blob/master/README.md

**Comment by midstar** [comment]
That link was not any happy reading for me who prefer a pure golang imaging library ;-) 

If we implement https://github.com/midstar/mediaweb/issues/11 the speed of thumbnail generation might not be that big of an issue.

**Comment by midstar** [comment]
Resampling filter was changed from Lanczos to Box in following release:

https://github.com/midstar/mediaweb/releases/tag/mediaweb-v1.0.0.132
